fix(pdu): associate the unexpected value with the error
This provides more useful errors:

Error: [invalid payload] PDU error

Caused by:
    [SendDataRequest] invalid message type (8)

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>